shellEmulator: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 1440

packages:
  - tooling
  - tooling/*
  - packages/*
  - packages/*/*
  - playground

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  vue-demi: false

overrides:
  glob@10.5.0: ^13.0.6
  glob@^7.2.3: ^13.0.6
